project:
  type: website

  preview:
    port: 5555
    browser: true
    watch-inputs: true
    navigate: true
    
  render:
    - "*.qmd"
    - "*.md"
    - "!etc/"
    
  resources:
    - "attachments/**"
    
freeze: true 
  
bibliography: attachments/bib/references.bib

# Metadata stuff
pagetitle: "{{< meta title >}} | Zhilin Su"
author-meta: "Zhilin Su"

website:
  title: "Zhilin Su"
  description: "Zhilin Su is a Psychology PhD student at Centre for Human Brain Health, University of Birmingham, studying social learning and group decision-making."
  favicon: "/attachments/favicon-512.png"
  site-url: https://zhilinsu.com/
  #repo-url: https://github.com/jhelvy/jhelvy_quarto
  
  #google-analytics: "XXX"
  
  open-graph: 
    image: "/attachments/profile/profile.jpg"
    locale: en_GB
    
  navbar:
    pinned: true
    
    left:
      - text: "About"
        href: "index.qmd"
      - text: "CV"
        href: "cv/index.qmd"
      - text: "Research"
        file: research/index.qmd
        
    right:
      - text: "{{< iconify fa6-brands bluesky size=1.1em title='Bluesky' >}}"
        href: https://bsky.app/profile/zhilinsu.bsky.social 
        rel: me
  
  page-footer:
    left: |
      <span class="faux-block">{{< ai orcid >}} <strong>ORCID</strong> [{{< var orcid >}}](https://orcid.org/{{< var orcid >}})</span>
    center: |
      <span class="faux-block">{{< fa brands creative-commons >}} {{< var years >}} Zhilin Su (inspired by [Andrew Heiss](https://www.andrewheiss.com/))</span>
      <span class="faux-block">[{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} Creative Commons CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)</span>  
    right: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>

format:
  html:
    theme: css/ath.scss
    grid: 
      body-width: 900px
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai
    
editor: source

