project:
  type: website
  
  output-dir: _site
  
  preview:
    port: 5555
    browser: true
    watch-inputs: true
    navigate: true
    
  render:
    - "index.qmd"
    
  resources:
    - "attachments/**"
    
freeze: true 
  
bibliography: attachments/bib/references.bib

# Metadata stuff
pagetitle: "{{< meta title >}} | Zhilin Su"
author-meta: "Zhilin Su"

website:
  title: "Zhilin Su"
  description: "The personal website of Zhilin Su"
  favicon: "/attachments/favicon-512.png"
  image: attachments/profile/zhilin-circle.png
  site-url: https://zhilinsu.com/
  favicon: attachments/favicon.ico
  #repo-url: https://github.com/jhelvy/jhelvy_quarto
  open-graph:
    locale: en_GB
    site-name: https://zhilinsu.com/
  navbar:
    right:
      - text: "About"
        href: about.qmd
format:
  html:
    theme: css/theme.scss
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: false
    
editor: source

